server:
  port: 8071

spring:
  task:
    scheduling:
      pool:
        size: 30
  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100
queueconfig:
  case-update-subscription: event_case-update_rh
  uac-update-subscription: event_uac-update_rh
  uac-authentication-topic: event_uac-authentication
  shared-pubsub-project: shared-project


cloud-storage:
  case-schema-name: case
  uac-schema-name: uac
  backoff:
    initial: 100
    multiplier: 1.2
    max: 16000
    max-attempts: 30

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  health:
    pubsub:
      enabled: false

messagelogging:
  logstacktraces: false

logging:
  profile: DEV
  level:
    root: INFO
    com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter: ERROR

# TODO: Move to application-dev.yml and provision via Docker-dev & Terraform instead
jws_key:
  '{
      "keyId": "f008897e548d5c4fb9271e5a85f6fc4759301f26",
      "purpose": "authentication",
      "type": "private",
      "value": "-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEAiflKcRSyjo5iIx/Qhqm3tkoIvnaLDjf06LTiD4piyM1Y1V2A\nTMK5KFVRAmpHN8CaTEdieufY9cuywbPEaPqRpdlQr9xTix05mlUBs826ktCGD8UK\nHmNV6CgLYLaXzswBl5NDZTMX/9g4KdyadUpaJ3Z3Jrp7Brnb1vSVt8uBnjcfOhWs\nA7BuEYQqgIWw/hkGEBh0yMhvgSQda69gukFSfhsV4YcZ7qUTVctujIOOiVYkCsRR\nVAvIXenVb1f1BjwqLVnG5qRXUBXRTd1w5P90T5BTuBQcCQlvtNiCbxHoKrt6LGOp\n7dikgnU/jcsLsT4X3c49UnOB4zRQIde4v50yRqcwloZ/cDTmyWYEUZEAVHI9DZ4+\nR9M2J0XWIrtL/bHoGGMZdxGs4VkvMJ6YprER8krXiNQoxRVzRhWGHVpGLC/EZvnE\n65FhSc21vjd5n85Biax/Cxf1V3whjmc5O9ve/nOqsx3rWPYbFGvDYEdYAoah/IxW\n9mMt5SZCL0ifxQXkt39pd8eYPIhGCcZ7J1mPlAwzPFb35pWSBcokZ3XoJHPdEHKo\nyhOqvnujiIkjlIwgXOumNRzSLzUshVIJR9GRBm8QmV387qUjnI8baULGKlRyY48W\nBUs7M++tzpNFQtHGwwsV1V0A53pC3P3e4gg4h6Gp4romAeU+Md8k/bmuyn8CAwEA\nAQKCAgAUDPpYfJ2GQgLY/+KZ70gXYaLrquaCZndc6gyAHahFbjIer7vZa+LkjaF8\nLF21KHRD6YvSOKc68SNFKw68As3vwCkNpYMukEyytO/OZXNbqpoQ6J2T1PPDDS66\nG07sapFAqdH9fvNZ5t4il0CLEwcO/RRLuIXwcEoWbuzjDNwFVhVfp46b6qPUP9S9\nYLBb/N74r9Uo6JfruIfeAlqYNq36TY1cfPmzyKGKskmaefPY2X/bYLRA9oVjwHuX\n9rxQ76Vhec6B7hgSN1l3a1rgrI8GkP7ZnXKFja2CJoSuB3gp3ZzfnowvWHBv1QIr\nZPqKA3AMd9BJjyetEQkkIeljT0Di8zHBHo1PvuYHrJPt4uGD+THtRJK3sPtyVxx1\nGgt2QsxVxiLWmzk6annMGP3V+rKO1u3LRihOwC0OmZ4XInQsLlklGENsD3RZdEuc\nKNvJ8rsvyv1VFb0OhRZdAKWnxUeUuu6daWqfPv8dTdSkpZEcOkI5Mp0fNugOn95C\nTaw8TVsOPg0j+3dW9w2ePLE01nb9gUVOXRzweAIA96eM680BUngu6jwLIwCKQjRP\nqUEJqc3XiwX0pqvsVBYG6nUQg0eodeKxVTeBD4jbd5YgkjxoxxfbDXrEw3h/MCwj\neGlUnKkhmzADGkzjNFCrac6LtXajqsWSCk2c1mf0bVUS0t8I4QKCAQEA8vM9CHvJ\ng8ToyLWGRgZlyIqxiC0rNebU1BabQmTK9X71oOEZp2r2lSA24PmHTp0UfHewTFS2\nD3vlk4Vl70vruUv98xvBsmnMZtZWiSu2sFRYfJZ9VqZ0tDoRCMW3slQGo38qm0zT\nrPeu8NjOQQCMXe9QZ12i1EmKuI0VPIOr5bEgvzwx4/EQb1rWRr6WYze+ciI82kl0\nkNDPK3nENBzoOoAPUUVtYHTXFtIjaHqg5TAJ0DSPD1qToXtlGRPFYeTOE73+udXr\nW5QepgJgcSqb4gG6VPMtqsa0zLKS6gc/9IkmiwDI3Gcf7D1SgtUvYP4KhvZJZ6nf\nKbvC1k6e6ARCnQKCAQEAkWKK1a75C4HSWh6q2r5l71E0c9KjBRZ2m+1u/5ua3CqL\nhavRsaderZTfpXxQgYPFJQRJ9pU+bPk82PdXmtdz5WSkVohcpks4ycKvfX4cVc4o\nvgRKlNiAc7GstBJPE7vxL+DoF77dnzJVU7o6ciKDuSLUAtQTeg2ZVBgswdqsmPYZ\ndm+qFGB3ub/xvlOx+qYALAAFHtZKv8TzROAPAeBi1kyEWEAPNJAvW2UTDKSSmDjc\n6/0AIr2FbZE4SyFMBd7eNxymr4bbiBWX6v2BcazksJGA+sJWpxZY16Ekh6zVpzhI\nMqA5D2J5km7qbXAfI3S7pEqIOvKkuJXRfHx7NIhYywKCAQEAzmjZ8ds52jnxjJSs\n/9FvqHItYwT9MU5sg8SxJDd+OBUlmwmkQhkeZpR4C6v0yVWrkhQeNLvD8mPRKQSt\nFiHqpANsPp/WcT5x6u0vmFsLW8RNaYxx8Kx7eqPa1RkmeNvqx/3CtS8QqGPGvdl1\nYsSUfTpVlXx4WuQgd6tl34P/B6b1q4P43zBwRitm4bQLEUDLDS0JhmviHSdK3CUY\nDS6CHzGt0d6qjsi19S2T57BIAnBN5hbBdMn/o7KyshuaFxHOA/fn8vtMewHdCC38\nwijxR5MwO/xfUDiCY2dUaoC+VYQwuuhvvtHezVdMQtvc5Qrw5rlYpDou38YmQu2J\nFJaKAQKCAQAyRKREZg9uTyDwUBI7OAH+0VEViwsawz2XhG0QrDjLT1qWiWYjyv8N\nfaAmk+kyHuGXfvgj7k57V2IWks8TltNXyYiY8uU2CmREPrB275fUg0fLC6jN9l3T\noudYC8yTwjQOnfEh5Li0Rq8CGC4FMLHi3Yv4vmNNnE4bqZAwJu/uo4kCTnG8Qe6j\npx5q9H1hcOw2Snt6whVuYSbL9by6pV8HQcWwzdV0EzaMn1IK2Qxm3aJlZkEZwfXU\ngJW6RHUIwpqK67kmj7ZwQycX9TdAmssn0eeKzI8xjqSBShJbZwMoomk0N/oCu8XV\nP8yGsnHRzJbko3CfES6rNAIOzOu8qjgpAoIBAQDy59rUV9dGbUdi4DS6Vusx9KN9\nFklFM0f0jdO2CWuDBfUDWYchKWlareyje5Z6C3cNs6oj1RfoZMUG5eRP6H9soM50\neQESuoE4ldUGFkFIgp3u3zMt93szNF3UpRrggwxH3HG93yfdv3cjRi2nCooBfJov\nVNLcxv3flEMIeSEd/ZwmRVmgyQvmCLTcnN54DD6lqmgen2V8X7jzVgvvZnGb/cUs\nMu3iDvfTOJFIwV5V/QnJE5YR0VVlEfCDAtdgGLOTlsL7JVhprKVBwk5YHOstO1f9\nElAX2glYEw9KYC3sEH97PdFbQ7AadzwI7XuaAgdOEjSLpW1NAj81gjPR0Qn9\n-----END RSA PRIVATE KEY-----"
  }'

# TODO: Move to application-dev.yml and provision via Docker-dev & Terraform instead
jwe_key:
  '{
    "keyId": "bc26b780aa46f053291ba122062e6075656c2345",
    "purpose": "authentication",
    "type": "public",
    "value": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoJFv7Mnp1YQNNFBGwf/T\nAhLtjvZxwPJCV3nfLxC7rcdyYddsrKtda7E4c4nhPykPbnkpFqa4GGj7fHz8PS6T\ns/F72owfz8HJ2vHtOlClwOv9C6xl2qZ9TayVQLt2UNLSQrT18163svpF7pZWYmFe\nGqNeqO2UtY+xJb+uRAgwR5gVISglVDXWEtHMESQyVY5rXECMneuVcKmHKvVBLSpf\nRd7gnE53hO2GpzQgRcVkuf4wIg6oAoxuLBFgpSYUF8Bp/CjGAjKyzlx6trLj9PXM\nHzMIlVGrcmqqgdkpzPGjOSHOJHxZpCS264a1V2JUr+xdzmpoxaH1z3xnoUayBkWO\nW2AJNQwtIKV8MpUvglYkFPZgnZ0mT4DSLtNdgWxG+uxlHIk6DMU+/ghDTzEXrnwq\nfZYeAYj4+dQpYDDIpekThFhMSz5sKrttMM959Zu4WdpfP7TnIn3OrJmtHNEU4mZj\nGgO1oM5cGCTeAVRCAQbg3gqB0JcxD7PI3HhY4yDYW5zHOH1Wv0BxeLBMJmHJqUyD\nrFrfRWT6l8IgNk7WxFD6Vvz/6VXzrxTJO+BQ8LJaX3IW0/NFYq1t0MVuJ3tuXCe6\n/2lIQW+quzVe1saQPXH0hmZ9Q26h98WbWAsziF57kdgqakMGqMMVBv9/FshaKDPn\nVGfxlg5OusA1TBy7BMRwfa8CAwEAAQ==\n-----END PUBLIC KEY-----"
  }'

#TODO: Put something sensible here
eq:
  response-id-salt: SRM_PLACEHOLDER