spring:
#  task:
#    scheduling:
#      pool:
#        size: 30


  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100

      firestore:
        project-id: our-project

#  FIRESTORE_EMULATOR_HOST" value="localhost:8542"

queueconfig:
  case-update-subscription: event_case-update_rh
  uac-update-topic: event_uac-update_rh
  survey-update-event-topic: event_survey-update_rh
  collection-exercise-update-event-topic: event_collection-exercise-update_rh
  shared-pubsub-project: shared-project


cloud-storage:
  case-schema-name: case
  uac-schema-name: uac
  survey-schema-name: survey
  collection-exercise-schema-name: collection_exercise
  event-backup-schema-name: event-backup
  backoff:
    initial: 100
    multiplier: 1.2
    max: 16000
    max-attempts: 30

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/rh-service-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  profile: DEV
  level:
    root: INFO
    com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter: ERROR

caserefgeneratorkey: abc123

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
  leaderDeathTimeout: 120 #seconds

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 60   #seconds

ras-rm-party-service:
  connection:
    scheme: http
    host: localhost
    port: 8081
    username: admin
    password: secret

ras-rm-case-service:
  connection:
    scheme: http
    host: localhost
    port: 8171
