spring:
  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100

      firestore:
        project-id: our-project

queueconfig:
  case-update-subscription: event_case-update_rh
  uac-update-subscription: event_uac-update_rh
  shared-pubsub-project: shared-project


cloud-storage:
  case-schema-name: case
  uac-schema-name: uac
  survey-schema-name: survey
  collection-exercise-schema-name: collection_exercise
  event-backup-schema-name: event-backup
  backoff:
    initial: 100
    multiplier: 1.2
    max: 16000
    max-attempts: 30

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/rh-service-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  profile: DEV
  level:
    root: INFO
    com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter: ERROR

